#!/bin/bash
# Quick setup script - helps pull a compatible Ollama model on the host

echo "========================================================================"
echo "LangGraph Agent - Model Setup Helper"
echo "========================================================================"
echo ""
echo "This script provides commands to run ON YOUR HOST MACHINE"
echo "to set up Ollama models with tool calling support."
echo ""
echo "========================================================================"
echo "RECOMMENDED MODELS (with tool calling support):"
echo "========================================================================"
echo ""
echo "1. llama3.2 (2GB) - Fast, efficient, great for learning"
echo "   Command: ollama pull llama3.2"
echo ""
echo "2. qwen2.5:3b (2GB) - Fast alternative with good performance"
echo "   Command: ollama pull qwen2.5:3b"
echo ""
echo "3. llama3.1 (4.7GB) - More capable, larger context"
echo "   Command: ollama pull llama3.1"
echo ""
echo "4. phi3.5 (2.2GB) - Microsoft's efficient model"
echo "   Command: ollama pull phi3.5"
echo ""
echo "========================================================================"
echo "STEPS TO SETUP:"
echo "========================================================================"
echo ""
echo "1. Open a terminal ON YOUR HOST MACHINE (not in the dev container)"
echo ""
echo "2. Check if Ollama is running:"
echo "   ollama list"
echo ""
echo "3. Pull a recommended model (e.g., llama3.2):"
echo "   ollama pull llama3.2"
echo ""
echo "4. Verify the model is available:"
echo "   ollama list"
echo ""
echo "5. Back in this dev container, run:"
echo "   export OLLAMA_MODEL=llama3.2"
echo "   python setup_check.py"
echo ""
echo "========================================================================"
echo "QUICK START (copy-paste these commands on your HOST):"
echo "========================================================================"
echo ""
echo "ollama pull llama3.2"
echo ""
echo "Then in this container:"
echo ""
echo "export OLLAMA_MODEL=llama3.2"
echo "python agent.py"
echo ""
echo "========================================================================"
